version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-fridge
    environment:
      MYSQL_ROOT_PASSWORD: 54088
      MYSQL_DATABASE: fridge_db
      MYSQL_USER: xavier
      MYSQL_PASSWORD: 54088
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  app:
    build: .
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/fridge_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: xavier
      SPRING_DATASOURCE_PASSWORD: 54088
    ports:
      - "8080:8080"

volumes:
  mysql_data: